branches:
  only:
    - master
    - page-builder
sudo: required
cache:
  directories:
    - /home/travis/docker/
services:
  - docker
before_install:
- if [ -f ${DOCKER_CACHE_FILE} ]; then gunzip -c ${DOCKER_CACHE_FILE} | docker load; fi
- docker build -t fftf/bftn .
env:
  global:
    - DOCKER_CACHE_FILE=/home/travis/docker/cache.tar.gz
    - DOCKER_REPOSITORY=fftf
    - PUBLISH_BRANCH=test-pages
script:
- git branch -D ${PUBLISH_BRANCH} | true
- git checkout -b ${PUBLISH_BRANCH}
- make bftn
- make july12
- git commit -a --author="Travis Script <>" -m "building static assets"
- if [[ ${TRAVIS_BRANCH} == "page-builder" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then git push --quiet "https://${GH_TOKEN}@${GH_REF}" +${PUBLISH_BRANCH}; fi
- if [[ ${TRAVIS_BRANCH} == "page-builder" ]] && [[ ${TRAVIS_PULL_REQUEST} == "false" ]]; then mkdir -p $(dirname ${DOCKER_CACHE_FILE}) ; docker save $(docker history -q ${DOCKER_REPOSITORY}:${TRAVIS_COMMIT} | grep -v '<missing>') | gzip > ${DOCKER_CACHE_FILE}; fi
